### ISSUE TITLE
9.1.5 New Item Upgrade Interface won't work with LiteBag enabled

### ISSUE THREAD

**Issue by xelmortis** [xod-wow/LiteBag#11]
9.1.5 introduced a new item upgrade interface. Whenever I try to upgrade an item (like korthia items, or pvp items) i get a warning that the action was blocked by LiteBag and that I should disable it. I disabled all other addons and tried it with just LiteBag and I was able to repeat it.

**Comment by mbattersby** [comment]
Thanks, I'll have a look at this as soon as I can.

**Comment by Epidemedabear** [comment]
I get the same this is the error 

1x [ADDON_ACTION_FORBIDDEN] AddOn 'LiteBag' tried to call the protected function 'UpgradeItem()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `UpgradeItem'
[string "@Blizzard_ItemUpgradeUI\Blizzard_ItemUpgradeUI.lua"]:104: in function `OnConfirm'
[string "@FrameXML\StaticPopup.lua"]:325: in function `OnAccept'
[string "@FrameXML\StaticPopup.lua"]:5137: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by mbattersby** [comment]
Can you please try LiteBag 9.1.3 and see if it fixes your problem?

Thanks.

**Comment by xelmortis** [comment]
It worked for me. Thank you.
