### ISSUE TITLE
Can you make LiteBag auto open at the guild bank please.

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteBag#13]
GUILDBANKFRAME_OPENED
GUILDBANKFRAME_CLOSED

Are the appropriate events. Thank you, sir.

**Comment by mbattersby** [comment]
Sorry, COVID is running through my family and I haven't had time to look at this. I think it seems OK, it just depends if there's any Blizzard complications. I'll look at it when I get a chance.
