### ISSUE TITLE
Two bugs in 10.0 Beta

### ISSUE THREAD

**Issue by Priapaus** [xod-wow/LiteBag#15]
Interface/FrameXML/BankFrame.lua:32: attempt to call method 'GetBagID' (a nil value)
Interface/FrameXML/MainMenuBarBagButtons.lua:134: attempt to call method 'MatchesBagID' (a nil value)

Happens when opening and closing the Bank Reagent window.

**Comment by mbattersby** [comment]
Hopefully fixed, thanks for the bug report. I really appreciate it.

**Comment by arcadepro** [comment]
Got this while farming Dragonsoul raid on an alt.

`1x LiteBag/ReplaceBlizzard.lua:51: attempt to call method 'MatchesBagID' (a nil value)
[string "@LiteBag/ReplaceBlizzard.lua"]:51: in function `OpenBag'
[string "@FrameXML/AlertFrameSystems.lua"]:552: in function <FrameXML/AlertFrameSystems.lua:542>

Locals:
id = 0
(*temporary) = nil
(*temporary) = LiteBagBackpack {
 0 = <userdata>
 panels = <table> {
 }
 SetPortraitShown = <function> defined @SharedXML/PortraitFrame.lua:91
 GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
 OnUpdate = <function> defined @LiteBag/Frame.lua:122
 SetPortraitTextureRaw = <function> defined @SharedXML/PortraitFrame.lua:79
 OnShow = <function> defined @LiteBag/Frame.lua:52
 TitleContainer = Frame {
 }
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @SharedXML/PortraitFrame.lua:32
 Tabs = <table> {
 }
 DefaultPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @SharedXML/PortraitFrame.lua:36
 ShowPanel = <function> defined @LiteBag/Frame.lua:106
 FrameType = "BACKPACK"
 SetBorder = <function> defined @SharedXML/PortraitFrame.lua:62
 layoutType = "HeldBagLayout"
 MovingAllowed = true
 SetPortraitToBag = <function> defined @SharedXML/PortraitFrame.lua:75
 SetPortraitAtlasRaw = <function> defined @SharedXML/PortraitFrame.lua:83
 SetPortraitToUnit = <function> defined @SharedXML/PortraitFrame.lua:71
 ResizeToPanel = <function> defined @LiteBag/Frame.lua:44
 SetSnapPosition = <function> defined @LiteBag/Frame.lua:27
 numTabs = 1
 GetPortrait = <function> defined @SharedXML/PortraitFrame.lua:58
 SetTitleFormatted = <function> defined @SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 OnLoad = <function> defined @LiteBag/Frame.lua:112
 CheckSnapPosition = <function> defined @LiteBag/Frame.lua:35
 Bg = Frame {
 }
 SetPortraitToAsset = <function> defined @SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:95
 GetCurrentPanel = <function> defined @LiteBag/Frame.lua:76
 CloseButton = Button {
 }
 PortraitContainer = Frame {
 }
 SetUpPanels = <function> defined @LiteBag/Frame.lua:81
 AddPanel = <function> defined @LiteBag/Frame.lua:96
 OnHide = <function> defined @LiteBag/Frame.lua:59
 selectedTab = 1
 SetPortraitTexCoord = <function> defined @SharedXML/PortraitFrame.lua:87
}
(*temporary) = 0
(*temporary) = "attempt to call method 'MatchesBagID' (a nil value)"
LB = <table> {
 CallHooks = <function> defined @LiteBag/Hooks.lua:26
 Options = Frame {
 }
 EventDebug = <function> defined @LiteBag/Print.lua:31
 Print = <function> defined @LiteBag/Print.lua:18
 AddPluginEvent = <function> defined @LiteBag/Hooks.lua:34
 UnregisterHook = <function> defined @LiteBag/Hooks.lua:22
 Localize = <table> {
 }
 UnregisterPluginEvents = <function> defined @LiteBag/Hooks.lua:49
 RegisterPluginEvents = <function> defined @LiteBag/Hooks.lua:39
 db = <table> {
 }
 IsPluginEvent = <function> defined @LiteBag/Hooks.lua:45
 Debug = <function> defined @LiteBag/Print.lua:23
 RegisterHook = <function> defined @LiteBag/Hooks.lua:17
}
`
