### ISSUE TITLE
Suggestion: An option to hide bag elements. (Bag buttons, search bar, addon name, clean button)

### ISSUE THREAD

**Issue by Nillx** [xod-wow/LiteBag#16]
Heya, im liking the addon so far. Do you think its possible to add an option to hide some elements like the bags on top, search bar and the clean icon? Maybe the addon name as well? Doing that will surely make the whole window a bit smaller and look clean.

![image](https://user-images.githubusercontent.com/34476875/202867155-0940b445-e373-47bb-a663-b3839596de3e.png)

**Comment by mbattersby** [comment]
LiteBag has been around for 10 years, this is just how it works. I'm not planning on a lot of extra options like hiding various parts. You can probably find other bag addons that have a heap of customization that might suit you better.

Best wishes, X.

**Comment by Nillx** [comment]
No problem.
