### ISSUE TITLE
Talking to the upgrade guy in Oribos opens a blank bank frame.

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteBag#19]
Talk to Aggressor Zo'dash in Oribos. Both the player's bank frame (empty, obviously) and bag frame are opened.

PLAYER_INTERACTION_MANAGER_FRAME_SHOW 53

Repro steps below : https://github.com/xod-wow/LiteBag/issues/19#issuecomment-1326950990

**Comment by mbattersby** [comment]
ooh, cool!

**Comment by mbattersby** [comment]
I've been trying to find an example of PLAYER_INTERACTION_MANAGER_FRAME_SHOW but didn't know how to trigger it!

**Comment by mbattersby** [comment]
Incredibly, this seems to be a blizzard bug!

With no addons loaded following your repro steps the game fires BANKFRAME_OPENED when interacting with the Item Upgrades NPC. They have very obviously messed up the half-transition to PLAYER_INTERACTION_MANAGER_FRAME_SHOW (and HIDE) and are triggering BANKFRAME_OPENED for more than just the bank NPC.

I think it'll take me a little while to figure out exactly how I should handle it.
