### ISSUE TITLE
Error related to row gaps settings

### ISSUE THREAD

**Issue by lenoirrichelieu** [xod-wow/LiteBag#24]
Hi,
I found an error when modifying the space between rows. If you set first time the row gap to 1 all works fine. But then, if you want to reverse to 0 (or other number) everything goes wrong. And even with gap set at 0 you'll never have rows one near each other. There is no error on bugsack to post so I attached two screenshots to make myself clear.

![error row gaps 2](https://user-images.githubusercontent.com/94080045/204876156-00fa11ed-74e6-40c1-b534-1b21523ae3ae.jpg)
![error row gaps 1](https://user-images.githubusercontent.com/94080045/204876162-0e0d88df-c4af-413d-93d5-01b32a011e22.jpg)

**Comment by mbattersby** [comment]
Woah that happens for me too!

**Comment by mbattersby** [comment]
Fixed in 10.0.5, thanks.
