### ISSUE TITLE
Integration with Caerdon Wardrobe not working

### ISSUE THREAD

**Issue by erendur81** [xod-wow/LiteBag#25]
Hi, somehow the integration with Caerdon Wardrobe is not working. Not icons or information are shown in the bag. It is working for the blizzard default bags and also for the vendors.

**Comment by mbattersby** [comment]
By the look of it they have taken the LiteBag support out of Caerdon Wardrobe. You'll need to log it with them and tell them LiteBag is still alive!

https://github.com/Caerdon/CaerdonWardrobe/issues

**Comment by erendur81** [comment]
I [asked ](https://github.com/Caerdon/CaerdonWardrobe/issues/34#issue-1471247955) for (re)adding the support.

**Comment by Caerdon** [comment]
Good to see it's still here!  This is fixed in v3.3.6.

**Comment by mbattersby** [comment]
I love Caerdon Wardrobe, this makes me happy!
