### ISSUE TITLE
Request: Add Support for classic currency display in inventory/bank

### ISSUE THREAD

**Issue by orionshock** [xod-wow/LiteBag#29]
Wrath Classic dosn't have all the API's for C_CurrencyInfo. Instead it uses GetBackpackCurrencyInfo

**Comment by mbattersby** [comment]
It does have GetBackpackCurrencyInfo, but I'm not sure it supports watching a currency?

Perhaps my (fresh DK) doesn't have any but I don't see any way to enable tracking of one (or even listing them).

I have a fix that I think would work, but I have no way to test it.

Any ideas?

**Comment by mbattersby** [comment]
I don't really understand what's going on but my classic branch is completely non-functional. Do you actually have a working LiteBag in wrath classic, or are you running on a private server?

**Comment by orionshock** [comment]
> I don't really understand what's going on but my classic branch is completely non-functional. Do you actually have a working LiteBag in wrath classic, or are you running on a private server?

I cheated :) 
I wrote a small stub of a mod that put all the bag/inventory API's back where they where before the changes and emulated their behavior otherwise.

I also have a patch waiting to update lite bags with all the api moves that blizzard did.

**Comment by mbattersby** [comment]
Ah, I see! I Fixed up all the obvious problems and it seems to be working,I think. I mostly just backported the ContainerFrame_Update from the classic source.

As I said before my level 60 death knight (highest level classic toon) doesn't have any currencies so I can't see the currency tab or put anything in the token frame to test it.

I'm a bit annoyed in how Blizzard are porting 1/3 of the retail API back to classic but leaving  other parts alone. It would be a lot nicer if they moved all of the container/bank stuff in one go. I didn't expect them to radically change the API between Wrath releases.

**Comment by mbattersby** [comment]
Hopefully 3.4.1-1wrath is a working release for WotLK Classic.

**Comment by mbattersby** [comment]
Closing this and hoping for the best.
