### ISSUE TITLE
Error calling LiteBagPanel_UpdateItemButtons

### ISSUE THREAD

**Issue by ronin-seven** [xod-wow/LiteBag#3]
Buying a bag slot in the bank results in this error:

1x LiteBag\LiteBagBank.lua:102: attempt to call global 'LiteBagPanel_UpdateItemButtons' (a nil value)
[string "@LiteBag\LiteBagBank.lua"]:102: in function <LiteBag\LiteBagBank.lua:70>

It appears this function was refactored in a commit 19 days ago but still referenced in:
1. LiteBagBank.lua:102
2. Frame.lua:166

**Comment by mbattersby** [comment]
Fixed for 9.0.4. Thanks.
