### ISSUE TITLE
Clean Up Bank button sometimes works incorrectly

### ISSUE THREAD

**Issue by sirzooro** [xod-wow/LiteBag#35]
Steps to reproduce:

- open bank
- switch to Reagent Bank tab
- close bank
- open bank again (reagent tab should appear here)
- addon displays Clean Up Bank button instead of Clean Up Reagent Bank one

**Comment by mbattersby** [comment]
Yep that's definitely a bug. I'll get a fix out asap.

Thanks for your excellent report on how to reproduce it.

**Comment by mbattersby** [comment]
Should be fixed in 10.0.16.
