### ISSUE TITLE
Option / Click to toggle KeyRing in Classic

### ISSUE THREAD

**Issue by orionshock** [xod-wow/LiteBag#36]
Option / Click to toggle KeyRing in Classic
:)
I know, i know, but having the key ring integrated into the bags and having to see it all the time is a drag :\

**Comment by mbattersby** [comment]
I don't play classic, but someone complained and said LiteBag needed to show the keyring. This is really the only place it can go as far as I can see, assuming it does need to be shown.

What do you think should happen? I have literally no idea what you mean by "toggle keyring" in the context of LiteBag.

**Comment by orionshock** [comment]
> I don't play classic, but someone complained and said LiteBag needed to show the keyring. This is really the only place it can go as far as I can see, assuming it does need to be shown.
 >.> yeah, that was me ... 

> What do you think should happen? I have literally no idea what you mean by "toggle keyring" in the context of LiteBag.

Clicking the key ring just hides the keyring rows/bag.
Other thing that would also work is when the keyring button is clicked
![image](https://user-images.githubusercontent.com/160723/229655920-09214d05-3633-4962-8fcd-1ab6ff4d46d2.png)
just pass it down to the default UI to deal with.

**Comment by orionshock** [comment]
<3 TY!

**Comment by mbattersby** [comment]
No problem. It's a bit of a hack but it seems to work.
