### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Falc101** [xod-wow/LiteBag#41]
I had been looking for a Bag addon for almost a year now, and after multiple installs of different addons, I have finally found one that perfectly fits me!!!!!!!!! I'm not even sure why it was so hidden behind all the others, but better late then never. Just wanted to compliment you and to say i appreciate you much for your project.  =)

**Comment by mbattersby** [comment]
Thanks for your kind words. It doesn't do much but it does what I want, I'm glad you enjoy it too.
