### ISSUE TITLE
Planned support for Classic Era?

### ISSUE THREAD

**Issue by Nillx** [xod-wow/LiteBag#45]
Hello, do you plan to update this addon for classic Era as well?

**Comment by mbattersby** [comment]
I think the classic client will also work on classic era, but I don't play either so I don't have any way to test it.

**Comment by Nillx** [comment]
I tested it today and it seems to be working fine, no errors. 

Sadly the Masque plugin doesnt work as it should but i guess thats not related to LiteBag.

**Comment by mbattersby** [comment]
Since it seems to work I've tagged the classic version as compatibly with classic_era on CurseForge etc.

I don't know anything about the Masque support sorry. I think it would be best to try to contact the author of that addon and see if they can help.
