### ISSUE TITLE
Request: Bag break option

### ISSUE THREAD

**Issue by tekkub** [xod-wow/LiteBag#46]
Love the addon, it does everything my old one-bag addon used to do except one thing... I'd like to have each bag on its own row.  Something like this:

```
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
```

If I were to set it to 20 wide columns, that'd look like this:

```
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐☐
```

It'd be bonus if you let us right-align the partial rows ^^

**Comment by mbattersby** [comment]
Oh wow, the tekkub! I used your wow-ui-source repo for so long, I don't think I would have gotten anywhere without it.

And LibDataBroker longer than I can even remember. You're a legend. Thanks!

I *think* you can already do what you want by selecting "Icon layout: Bags" in the settings. Well, the first half of what you want anyway.

![image](https://github.com/xod-wow/LiteBag/assets/1300207/3d983562-c257-46e2-8a49-9c96811b9699)
![image](https://github.com/xod-wow/LiteBag/assets/1300207/71180038-45ef-46d8-a1ff-d75f332cfd5c)

The right-aligning is technically in the code I've just never put it in. I'll do so

**Comment by mbattersby** [comment]
Hmm I thought I had an easy fix for the right-align but I realize it's not quite what you're after since it does the bags from bottom to top. I'll have to have a poke at it when I have more time and see if I can sensibly separate out right-to-left from bottom-to-top.

**Comment by tekkub** [comment]
Ah! I should have tried all the settings before I opened an issue... 

You don't have to do the right-align thing, I was just pondering the aesthetics of the wrapped rows... I personally crank the columns so that each row is a bag.

Glad you like LDB, I was just reminiscing the other day about a friend who didn't know I made it complaining at me that he didn't like the design of it :)

**Comment by mbattersby** [comment]
The latest release, 10.2.0-4, should allow you to set the starting icon position so you can get the R-to-L and Top-to-Bottom setting you are after.

I thought it was a good idea, so I did it.

You should be very proud of LDB. To last so long unchanged is a testament to the greatness of the design.

**Comment by F-Lambda** [comment]
Bit niche, but kind of related: Would it be possible to set it so that the reagent bag and merged regular bags are shown next to each other? Kind of like this:

```
Reagent   Regular
☐☐☐☐☐  ☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐  ☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐  ☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐  ☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐  ☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐  ☐☐☐☐☐☐☐☐☐☐
☐☐☐☐☐  ☐☐☐☐☐☐☐☐☐☐
         ☐☐☐☐☐☐☐☐☐☐
         ☐☐☐☐☐☐☐☐☐☐
         ☐☐☐☐☐☐☐☐☐☐
         ☐☐☐☐☐☐☐☐☐☐
         ☐☐☐☐☐☐☐☐☐☐
```

**Comment by mbattersby** [comment]
No, sorry. I think if you want arbitrary bag layouts you're probably better off with a different addon. LiteBag is pretty much top to bottom or bottom to top.

Happy adventuring, X.
