### ISSUE TITLE
Bug Report from past week

### ISSUE THREAD

**Issue by rwheaton1** [xod-wow/LiteBag#48]
I just returned to WoW and was told that many people moved from Bagnon to this one.  This is the first time ever I'm reporting bugs but I've been getting so many it is interfering with their new UI.  Here iare the error(s) I received:

1x [ADDON_ACTION_BLOCKED] AddOn 'LiteBag' tried to call the protected function 'ActionButton1:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:503: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:980: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:207: in function <FrameXML/ActionButton.lua:204>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

3x [ADDON_ACTION_BLOCKED] AddOn 'LiteBag' tried to call the protected function 'PrimaryProfession2SpellButtonBottom:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Show'
[string "@FrameXML/SpellBookFrame.lua"]:1557: in function `FormatProfession'
[string "@FrameXML/SpellBookFrame.lua"]:1600: in function `SpellBook_UpdateProfTab'
[string "@FrameXML/SpellBookFrame.lua"]:163: in function <FrameXML/SpellBookFrame.lua:142>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

1x [ADDON_ACTION_BLOCKED] AddOn 'LiteBag' tried to call the protected function 'MultiBarBottomLeftButton1:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetShown'
[string "@FrameXML/ActionBar.lua"]:196: in function `UpdateShownButtons'
[string "@FrameXML/ActionButton.lua"]:507: in function <FrameXML/ActionButton.lua:492>
[string "=[C]"]: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:980: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:207: in function <FrameXML/ActionButton.lua:204>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

1x [ADDON_ACTION_BLOCKED] AddOn 'LiteBag' tried to call the protected function 'MultiBar7Button1:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetShown'
[string "@FrameXML/ActionBar.lua"]:196: in function `UpdateShownButtons'
[string "@FrameXML/ActionButton.lua"]:507: in function <FrameXML/ActionButton.lua:492>
[string "=[C]"]: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:980: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:207: in function <FrameXML/ActionButton.lua:204>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by mbattersby** [comment]
This is what Blizzard calls "taint", addons interfering with the default UI elements and causing them to stop working (mostly) in combat.

Unfortunately what addon is responsible isn't correctly reported by the error messages. I'm 99% sure LiteBag isn't the cause, as I haven't had any taint issues in many many months and nobody else has reported any.

I don't think there's any good way to track it down except for disabling addons and trying to see which one caused it. If you get a taint error with only LiteBag loaded and no other addons please report it here #34.
