### ISSUE TITLE
Item highlighting is not cleared properly

### ISSUE THREAD

**Issue by sirzooro** [xod-wow/LiteBag#49]
Steps to reproduce:
- open bags by clicking on any bag icon in bottom right corner of the screen - bags will open and cells for pointed bag will be highlighted;
- click on bag icon again to close bags;
- move cursor somewhere else and open bags using B key;
- cells which were highlighted previously are still highlighted

**Comment by mbattersby** [comment]
Classic or retail wow?

**Comment by sirzooro** [comment]
Retail

**Comment by mbattersby** [comment]
Definitely a bug, thanks for the excellent bug report. I'll fix it up when I get a chance.

**Comment by mbattersby** [comment]
I think I have an ok work around, should be fixed in 10.2.5-2.
