### ISSUE TITLE
Dc when using Litebag

### ISSUE THREAD

**Issue by Tannx1980** [xod-wow/LiteBag#51]
Both me and my sister are disconnecting when fight in the emerald dream when I am using Ray of frost. Let me know what the name of the file you need to look into this. I forgot the name. Litebag is the only she is using. I am using other ones. Once I know the name of the file, I can send both logs.

**Comment by mbattersby** [comment]
I can't think of any way LiteBag would cause this, or any logs that would help. 

Here is a video of me using Ray of Frost in Emerald Dream without disconnecting. Would this disconnect you?

https://youtu.be/Ewl8IVYL4dY

What is different between us?

Did this just start happening with 10.2.7?

If your sister deactivates LiteBag (no addons) it does not disconnect? But it always disconnects with LiteBag loaded?

What is your game latency?
![image](https://github.com/xod-wow/LiteBag/assets/1300207/01661240-eabe-48d0-87ed-9b87a834af71)

What language are you running wow in?
![image](https://github.com/xod-wow/LiteBag/assets/1300207/b1e4cb2e-07da-4380-a76e-5b7a2ea9f3b5)

**Comment by Tannx1980** [comment]
Yes it started on Tuesday 23th. It says that I am running 10.2.6. which is current verison. I am running the American English verison of the client. We both on the same network. I was running other addons maybe since we are the same network it caused it its working now. On both of our accounts.

**Comment by mbattersby** [comment]
I'm glad it's working now, if it happens again and you can figure out why please let me know.
