### ISSUE TITLE
Hiding reagent bag on Blizzard icon order does not work as intended.

### ISSUE THREAD

**Issue by Dillonzer** [xod-wow/LiteBag#52]
Not hidden: ![image](https://github.com/xod-wow/LiteBag/assets/7096155/c301f699-8b64-4cba-b454-7fb0b2340598)
Hidden: ![image](https://github.com/xod-wow/LiteBag/assets/7096155/434f7f50-b7ec-4c24-8962-8f673d040935)

I just downloaded the addon so running the latest version.

**Comment by mbattersby** [comment]
Can you paste a screenshot of your options panel for litebag? Thanks.

**Comment by mbattersby** [comment]
It's definitely broken, but it's been so long since I looked at this I can't figure out what the purpose of the "blizzard" option is or if it even makes sense any more.

**Comment by mbattersby** [comment]
Fixed in 10.2.7-2.
