### ISSUE TITLE
Cata Classic: Tracked Currency Doesn't Update

### ISSUE THREAD

**Issue by Clamsoda** [xod-wow/LiteBag#55]
The currency frame, and your implementation of tracked currency on the container frames, don't update in real time when spending currency.  You must close the frame and re-open it up to force the currency to refresh.

I added this code to force your token frame to update on CURRENCY_DISPLAY_UPDATE.  I saw your comment in your code, I am sure you can make a better implementation.

```Lua
local eventHandler = CreateFrame("Frame")
eventHandler:RegisterEvent("CURRENCY_DISPLAY_UPDATE")
eventHandler:SetScript("OnEvent", function()
    BackpackTokenFrame_Update()
end)
```

**Comment by mbattersby** [comment]
Ah, excellent news,they've added CURRENCY_DISPLAY_UPDATE. That will make life much easier, I can hopefully backport the way it works for retail so it's all done the same way.

**Comment by mbattersby** [comment]
Should be fixed in 4.4.0-3-cata

Please test, I have no way to test it.

**Comment by Clamsoda** [comment]
Works perfect.

**Comment by mbattersby** [comment]
Terrific, thanks for letting me know.
