### ISSUE TITLE
Crashing when sorting bank with only litebag installed

### ISSUE THREAD

**Issue by Tannx1980** [xod-wow/LiteBag#58]
I am having a crash when shorting my bank here is the error message
Message: Interface/AddOns/LiteBag/ContainerPanel.lua:203: attempt to index local 'info' (a nil value)
Time: Wed Jul 24 12:51:16 2024
Count: 7
Stack: Interface/AddOns/LiteBag/ContainerPanel.lua:203: attempt to index local 'info' (a nil value)
[string "@Interface/AddOns/LiteBag/ContainerPanel.lua"]:203: in function <Interface/AddOns/LiteBag/ContainerPanel.lua:184>
[string "=[C]"]: in function `SortBankBags'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/BankFrame.lua"]:535: in function <...AddOns/Blizzard_UIPanels_Game/Mainline/BankFrame.lua:530>

Locals: self = LiteBagBankPanel {
 resizingAllowed = true
 showMoneyFrame = true
 bagFrames = <table> {
 }
 showSearchBox = true
 Items = <table> {
 }
 Title = "Bank"
 bagIDs = <table> {
 }
 width = 599
 size = 248
 bagButtons = <table> {
 }
 containsBags = <table> {
 }
 MoneyFrame = LiteBagBankPanelMoneyFrame {
 }
 showTokenTracker = false
 PortraitButton = LiteBagBankPanelPortraitButton {
 }
 height = 850.000001
 PanelType = "BANK"
}
event = "ITEM_LOCK_CHANGED"
arg1 = -1
arg2 = 35
bag = LiteBagBankPanelBag1 {
 Items = <table> {
 }
 size = 28
}
info = nil
(*temporary) = nil
(*temporary) = 35
(*temporary) = "attempt to index local 'info' (a nil value)"
LB = <table> {
 Manager = LiteBagManager {
 }
 db = <table> {
 }
 Localize = <table> {
 }
}

**Comment by mbattersby** [comment]
Thanks I'll look into this asap.
