### ISSUE TITLE
Right-click to store item in warband bank always stores the item in the 1st warband bank tab regardless of the warband bank tab being active.

### ISSUE THREAD

**Issue by bigos81** [xod-wow/LiteBag#59]
# Brief description
Right now when right-clicking on an item in character bag while having warband bank open the item always is put into first warband bank tab, rather than the tab that is currently opened.

# To reproduce:
1. Open bank interface by interacting with a banker NPC
2. Open warband bank
3. Select any tab from warband bank other than first
4. Right-click the item to store in warband bank

# Expected outcome:
1. The item* is placed in currently opened warband bank tab

# Current behaviour:
1. The item* is placed in first warband bank tab

# Additional remarks:
[*] the item needs to be of appropriate type to be stored in warband bank

**Comment by mbattersby** [comment]
This isn't a LiteBag bug, it's just how Blizzard do it. Works the same with the default UI.
