### ISSUE TITLE
Cataclysm Classic 4.4.1 InterfaceOptions_AddCategory

### ISSUE THREAD

**Issue by Clamsoda** [xod-wow/LiteBag#64]
2x LiteBag/UI/UIOptionsPanelTemplate.lua:111: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@LiteBag/UI/UIOptionsPanelTemplate.lua"]:111: in function <LiteBag/UI/UIOptionsPanelTemplate.lua:92>

Locals:
self = LiteBagOptions {
 controls = <table> {
 }
 title = LiteBagOptionsTitle {
 }
 name = "LiteBag"
}
(*temporary) = nil
(*temporary) = LiteBagOptions {
 controls = <table> {
 }
 title = LiteBagOptionsTitle {
 }
 name = "LiteBag"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"

**Comment by mbattersby** [comment]
Thanks, fixed in 4.4.1-1-cata
