### ISSUE TITLE
Crashing on Character

### ISSUE THREAD

**Issue by Tannx1980** [xod-wow/LiteBag#7]
Here is error message
Message: Usage: local isAzeriteEmpoweredItem = C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID(itemInfo)
Time: Wed Jun 30 09:48:13 2021
Count: 1
Stack: Usage: local isAzeriteEmpoweredItem = C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID(itemInfo)
[string "=[C]"]: in function `IsAzeriteEmpoweredItemByID'
[string "@Interface\FrameXML\ContainerFrame.lua"]:442: in function `ContainerFrame_ConsiderItemButtonForAzeriteTutorial'
[string "@Interface\AddOns\LiteBag\Panel.lua"]:427: in function `LiteBagPanel_UpdateBag'
[string "@Interface\AddOns\LiteBag\Panel.lua"]:442: in function `LiteBagPanel_UpdateAllBags'
[string "@Interface\AddOns\LiteBag\Panel.lua"]:461: in function <Interface\AddOns\LiteBag\Panel.lua:457>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\LiteBag\ReplaceBlizzard.lua"]:49: in function `OpenAllBags'
[string "@Interface\FrameXML\MailFrame.lua"]:65: in function <Interface\FrameXML\MailFrame.lua:52>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals: (*temporary) = "Usage: local isAzeriteEmpoweredItem = C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID(itemInfo)"[](url)

**Comment by mbattersby** [comment]
Please try LiteBag 9.1.1 and let me know if it fixes your issue.
