### ISSUE TITLE
Broken since v9.1.0 update

### ISSUE THREAD

**Issue by 2case** [xod-wow/LiteBag#8]
- Bags look empty (except the base backpack)
- Many slots have a glowing blue border (bags only)
- Stacks dont update for example while cooking (bags & backpack)
- Tooltip on hovering work
- Movement work, but slots are not update after drop
- Same with the bank

Greetings,
Tom.

**Comment by mbattersby** [comment]
I think this is Blizzard changes to the Item Tutorial system. Hopefully fixed in LiteBag 9.1.1.

**Comment by 2case** [comment]
Bugs are fixed with the new update!

Thanks,
Tom.
